/var/spool/slurm/slurmd/job8493809/slurm_script: line 8: activate: No such file or directory
Running benchmark `H2OAutoML` on `openml/t/211979` framework in `local` mode.
Loading frameworks definitions from ['/home/juradoi/experiments/automlbenchmark/resources/frameworks.yaml'].
Loading benchmark constraint definitions from ['/home/juradoi/experiments/automlbenchmark/resources/constraints.yaml'].
Loading openml task 211979.
no element found: line 1, column 0
Traceback (most recent call last):
  File "/home/juradoi/miniconda3/envs/venv/lib/python3.8/site-packages/openml/datasets/dataset.py", line 923, in _read_features
    with open(features_pickle_file, "rb") as fh_binary:
FileNotFoundError: [Errno 2] No such file or directory: '/home/juradoi/.cache/openml/org/openml/www/datasets/41168/features.xml.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "runbenchmark.py", line 163, in <module>
    bench = amlb.Benchmark(args.framework, args.benchmark, args.constraint)
  File "/home/juradoi/experiments/automlbenchmark/amlb/benchmark.py", line 84, in __init__
    self.benchmark_def, self.benchmark_name, self.benchmark_path = rget().benchmark_definition(benchmark_name, self.constraint_def)
  File "/home/juradoi/experiments/automlbenchmark/amlb/resources.py", line 185, in benchmark_definition
    hard_defaults, tasks, benchmark_path, benchmark_name = benchmark_load(name, self.config.benchmarks.definition_dir)
  File "/home/juradoi/experiments/automlbenchmark/amlb/benchmarks/parser.py", line 19, in benchmark_load
    benchmark_name, benchmark_path, tasks = load_oml_benchmark(name)
  File "/home/juradoi/experiments/automlbenchmark/amlb/benchmarks/openml.py", line 41, in load_oml_benchmark
    t = openml.tasks.get_task(oml_id, download_data=False, download_qualities=False)
  File "/home/juradoi/miniconda3/envs/venv/lib/python3.8/site-packages/openml/tasks/functions.py", line 376, in get_task
    raise e
  File "/home/juradoi/miniconda3/envs/venv/lib/python3.8/site-packages/openml/tasks/functions.py", line 361, in get_task
    dataset = get_dataset(task.dataset_id, download_data, download_qualities=download_qualities)
  File "/home/juradoi/miniconda3/envs/venv/lib/python3.8/site-packages/openml/datasets/functions.py", line 449, in get_dataset
    dataset = _create_dataset_from_description(
  File "/home/juradoi/miniconda3/envs/venv/lib/python3.8/site-packages/openml/datasets/functions.py", line 1159, in _create_dataset_from_description
    return OpenMLDataset(
  File "/home/juradoi/miniconda3/envs/venv/lib/python3.8/site-packages/openml/datasets/dataset.py", line 216, in __init__
    self.features = _read_features(
  File "/home/juradoi/miniconda3/envs/venv/lib/python3.8/site-packages/openml/datasets/dataset.py", line 928, in _read_features
    xml_dict = xmltodict.parse(
  File "/home/juradoi/miniconda3/envs/venv/lib/python3.8/site-packages/xmltodict.py", line 327, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 1, column 0
